language: generic

matrix:
  include:
    - name: "Official Zandronum Build"
      env:
      - BUILD_REPO_URL=https://bitbucket.org/Torr_Samaho/zandronum-stable
      - BUILD_REPO_TAG=ZA_3.0.1
      - BUILD_IMAGE_TAGS="official-latest official-3.0"
    - name: "TSPG Zandronum Build"
      env:
      - BUILD_REPO_URL=https://bitbucket.org/thesentinelsplayground/zatspg-release
      - BUILD_REPO_TAG=TSPGv14
      - BUILD_IMAGE_TAGS="tspg-latest tspg-v14"

script:
- ./travis-scripts/build-image.sh $BUILD_REPO_URL $BUILD_REPO_TAG $BUILD_IMAGE_TAGS
- |
  if [[ $TRAVIS_BRANCH == "master" && $TRAVIS_PULL_REQUEST == "false" ]]; then
      ./travis-scripts/push-images.sh
  fi
